config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :items, only: [:index, :show]

  resources :carts, only: [:create]

  resources :users, only: [:create, :update]

  resources :orders, only: :update

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  put '/cart', to: 'carts#update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/merchants', to: 'users#index'

  scope :dashboard, module: :merchant, as: :dashboard do
    get '/', to: 'users#show'
    resources :items, only: [:index, :new, :edit, :update]
  end

  namespace :merchant do
    resources :items, except: [:show, :index, :new, :edit, :update]

    put '/items/:id/enable', to: 'items#enable', as: :enable_item
    put '/items/:id/disable', to: 'items#disable', as: :disable_item
  end

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show, :create]
    get '/', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :reviews, except: [:show, :new, :create]
  end

  resources :order_items, only: [:create] do
    resources :reviews, only: [:new, :create]
  end

  scope :dashboard, as: :merchant, module: :merchant do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :edit]
    put '/users/:id/enable', to: 'users#enable', as: :enable_user
    put '/users/:id/disable', to: 'users#disable', as: :disable_user
    put 'users/:id/upgrade', to: 'users#upgrade', as: :upgrade_user
    put '/merchant/:id/downgrade', to: 'merchants#downgrade', as: :downgrade_merchant
    get '/dashboard', to: 'dashboard#show'
    resources :merchants, only: [:show, :update] do
      resources :items, except: :show
      put '/items/:id/enable', to: 'items#enable', as: :enable_item
      put '/items/:id/disable', to: 'items#disable', as: :disable_item
    end
    resources :orders, only: [:index, :show, :update]
  end
end

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
<div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<% flash.clear %>

app/views/shared/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <%= link_to "Store64", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to 'Items', items_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'Merchants', merchants_path, class: "nav-link" %></li>
      <% if current_user %>
      <%= render partial: 'shared/nav/registered' if current_user.registered? %>
      <%= render partial: 'shared/nav/merchant' if current_user.merchant? %>
      <%= render partial: 'shared/nav/admin' if current_user.admin? %>
      <li class="nav-item"><%= link_to 'Logout', logout_path, class: "nav-link" %></li>
      <% else %>
      <%= render partial: "shared/nav/visitor" %>
      <% end %>
    </ul>
  </div>
  <span class="navbar-text"><%= "Logged in as: #{current_user.name}" if current_user %></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>