config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :items, only: [:index, :show]

  resources :carts, only: [:create]

  resources :users, only: [:create, :update]

  resources :orders, only: :update

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  put '/cart', to: 'carts#update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/merchants', to: 'users#index'

  scope :dashboard, module: :merchant, as: :dashboard do
    get '/', to: 'users#show'
    resources :items, only: [:index, :new, :edit, :update]
  end

  namespace :merchant do
    resources :items, except: [:show, :index, :new, :edit, :update]

    put '/items/:id/enable', to: 'items#enable', as: :enable_item
    put '/items/:id/disable', to: 'items#disable', as: :disable_item
  end

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show, :create]
    get '/', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :reviews, except: [:show, :new, :create]
  end

  resources :order_items, only: [:create] do
    resources :reviews, only: [:new, :create]
  end

  scope :dashboard, as: :merchant, module: :merchant do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :edit]
    put '/users/:id/enable', to: 'users#enable', as: :enable_user
    put '/users/:id/disable', to: 'users#disable', as: :disable_user
    put 'users/:id/upgrade', to: 'users#upgrade', as: :upgrade_user
    put '/merchant/:id/downgrade', to: 'merchants#downgrade', as: :downgrade_merchant
    get '/dashboard', to: 'dashboard#show'
    resources :merchants, only: [:show, :update] do
      resources :items, except: :show
      put '/items/:id/enable', to: 'items#enable', as: :enable_item
      put '/items/:id/disable', to: 'items#disable', as: :disable_item
    end
    resources :orders, only: [:index, :show, :update]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :image

  validates :quantity,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0,
      only_integer: true
  }

  validates :price,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0
  }

  validates :name,
    presence: true,
    length: {minimum: 1}

  validates :description,
    presence: true,
    length: {minimum: 1}

  def self.enabled_items
    Item.where(disabled: false)
  end

  def self.top_items(limit)
    items_by_quantity(limit, "desc")
  end

  def self.worst_items(limit)
    items_by_quantity(limit, "asc")
  end

  def self.items_by_quantity(limit, order)
    Item.select(:id, :name, "SUM(order_items.quantity) as quantity")
    .joins(:order_items)
    .where(order_items: {fulfilled: true})
    .group(:id)
    .order("quantity #{order}")
    .limit(limit)
  end

  def has_reviews?
    !(order_items.joins(:review).empty?)
  end

  def average_review_rating
    order_items.joins(:review).average(:rating)
  end

  def average_fulfillment_time
    if (order_items.count > 0) && (order_items.where({fulfilled: true})).count > 0
      Item.joins(:order_items)
          .where(id: self.id, order_items: {fulfilled: true})
          .select("avg(order_items.updated_at - order_items.created_at) as fulfillment_time")
          .group(:id)[0]
          .fulfillment_time
    elsif order_items.count > 0
      "This item has not been fulfilled"
    else
      "Never been ordered"
    end
  end

  def ordered?
    order_items.count > 0
  end

  def subtotal(quantity)
    price * quantity
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  def index
    @merchant = User.find(params[:merchant_id])
    @items = @merchant.items
    render :'merchant/items/index'
  end

  def new
    @merchant = User.find(params[:merchant_id])
    @item = @merchant.items.new
  end

  def create
    @merchant = User.find(params[:merchant_id])
    @item = @merchant.items.new(item_params)
    if @item.save
      flash[:success] = "You have added an item."
      redirect_to admin_merchant_items_path(@merchant)
    else
      flash[:danger] = "There are problems with the provided information."
      render :new
    end
  end

  def edit
    @merchant = User.find(params[:merchant_id])
    @item = Item.find(params[:id])
  end

  def update
    @merchant = User.find(params[:merchant_id])
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Item ##{@item.id} has successfully been updated."
      redirect_to admin_merchant_items_path(@merchant)
    else
      flash[:danger] = "There are problems with the provided information."
      render :edit
    end
  end

  def destroy
    item = Item.destroy(params[:id])
    flash[:danger] = "Item ##{params[:id]} has been deleted."
    redirect_to admin_merchant_items_path(item.user_id)
  end

  def enable
    Item.find(params[:id]).update(disabled: false)
    flash[:success] = "Item ##{params[:id]} is now available for sale."
    redirect_to admin_merchant_items_path(params[:merchant_id])
  end

  def disable
    Item.find(params[:id]).update(disabled: true)
    flash[:warning] = "Item ##{params[:id]} is no longer available for sale."
    redirect_to admin_merchant_items_path(params[:merchant_id])
  end

  private

  def item_params
    params[:item][:image] = "https://via.placeholder.com/200x300?text=Store64" if params[:item][:image] == ""
    params.require(:item).permit(:name, :description, :image, :price, :quantity)
  end
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController
  def show
    @user = User.find(params[:id])
    @orders = Order.pending_orders(@user)
    redirect_to admin_user_path(@user) if @user.registered?
    render '/merchant/users/show' if @user.merchant?
  end

  def downgrade
    @merchant = User.find(params[:id])
    @merchant.items.each do |item|
      item.update(disabled: 'true')
    end
    @merchant.update(role: 'registered')
    flash[:primary] = 'You have downgraded a merchant'
    redirect_to admin_user_path(@merchant)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.enabled_items
    @top_items = Item.top_items(5)
    @worst_items = Item.worst_items(5)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/merchant/base_controller.rb
class Merchant::BaseController < ApplicationController
  before_action :require_merchant

  def require_merchant
    render file: '/public/404' unless current_merchant?
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.items
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      flash[:success] = "You have added a new item."
      redirect_to dashboard_items_path
    else
      flash[:danger] = "There are problems with the provided information."
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Your item has been successfully updated."
      redirect_to dashboard_items_path
    else
      flash[:danger] = "There are problems with the provided information."
      render :edit
    end
  end

  def enable
    Item.find(params[:id]).update(disabled: false)
    flash[:success] = "Item ##{params[:id]} is now available for sale."
    redirect_to dashboard_items_path
  end

  def disable
    Item.find(params[:id]).update(disabled: true)
    flash[:warning] = "Item ##{params[:id]} is no longer available for sale."
    redirect_to dashboard_items_path
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:danger] = "Item ##{params[:id]} has been deleted."
    redirect_to dashboard_items_path
  end

  private

  def item_params
    params[:item][:image] = "https://via.placeholder.com/200x300?text=Store64" if params[:item][:image] == ""
    params.require(:item).permit(:name, :description, :image, :price, :quantity)
  end
end

app/controllers/merchant/orders_controller.rb
class Merchant::OrdersController < Merchant::BaseController
  def show
    @order = Order.find(params[:id])
    @customer = @order.user
    render '/orders/show'
  end

  def update
    order_item = OrderItem.find(params[:ordered_item])
    order_item.update(fulfilled: true)
    item = Item.find(order_item.item_id)
    new_quantity = item.quantity - order_item.quantity
    item.update(quantity: new_quantity)
    flash[:success] = "You have fulfilled #{item.name} from order ##{order_item.order_id}"
    order = Order.find(params[:id])
    if order.order_items.where(fulfilled: false).count == 0
      order.update(status: 'completed')
    end
    redirect_to merchant_order_path(order)
  end
end

app/controllers/merchant/users_controller.rb
class Merchant::UsersController < Merchant::BaseController
  def show
    @orders = Order.pending_orders(current_user)
    @user = current_user
  end
end

app/views/merchant/items/_errors.html.erb
<% if !@item.errors.empty? %>
<div class="alert alert-danger">
  <ul id="errors">
    <% @item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/merchant/items/_item.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.text_field :image, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :price %>
  <%= f.number_field :price, step: 0.01, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :quantity %>
  <%= f.number_field :quantity, class: "form-control" %>
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>

app/views/merchant/items/edit.html.erb
<%= render partial: 'merchant/items/errors' %>
<%= form_for @item, :url => {:controller => 'merchant/items', :action => 'update'} do |f| %>
<%= render partial: 'merchant/items/item', locals: {:f => f} %>
<% end %>

app/views/merchant/items/index.html.erb
<%= link_to "Add a new item", new_dashboard_item_path if current_merchant? %>
<%= link_to "Add a new item", new_admin_merchant_item_path(@merchant) if current_admin? %>
<section class="container">
  <section class="row">
    <% @items.each do |item| %>
    <div class='card col-12 col-md-6 col-lg-4 col-xl-3' id="item-<%= item.id %>">
      <%= image_tag(item.image, class: "card-img-top", alt: "#{item.name} image") %>
      <div class="card-body">
        <h5 class="card-title">Item #<%= item.id %> <%= item.name %></h5>
        <p class="card-text"><%= item.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Price: <%= number_to_currency(item.price) %></li>
        <li class="list-group-item">Current Stock: <%= item.quantity %></li>
        <li class="list-group-item"><%= link_to "Edit Item", edit_dashboard_item_path(item) if current_merchant? %>
        <%= link_to "Edit Item", edit_admin_merchant_item_path(@merchant, item) if current_admin? %></li>
        <li class="list-group-item"><%= button_to "Delete Item", merchant_item_path(item), class: 'btn btn-danger', method: :delete if !item.ordered? && current_merchant? %>
        <%= button_to "Delete Item", admin_merchant_item_path(@merchant, item),class: 'btn btn-danger', method: :delete if !item.ordered? && current_admin? %>
        <%= button_to "Enable Item", admin_merchant_enable_item_path(@merchant, item), class: 'btn btn-success', method: :put if item.ordered? && item.disabled && current_admin? %>
        <%= button_to "Enable Item", merchant_enable_item_path(item), class: 'btn btn-success', method: :put if item.ordered? && item.disabled && current_merchant? %>
        <%= button_to "Disable Item", admin_merchant_disable_item_path(@merchant, item), class: 'btn btn-warning', method: :put if item.ordered? && !item.disabled && current_admin? %>
        <%= button_to "Disable Item", merchant_disable_item_path(item), class: 'btn btn-warning', method: :put if item.ordered? && !item.disabled && current_merchant?%></li>
      </ul>
    </div>
    <% end %>
  </section>
</section>

app/views/merchant/items/new.html.erb
<% if @item.errors %>
<ul id="errors">
  <% @item.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<%= render partial: 'merchant/items/item' %>