config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :items, only: [:index, :show]

  resources :carts, only: [:create]

  resources :users, only: [:create, :update]

  resources :orders, only: :update

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  put '/cart', to: 'carts#update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/merchants', to: 'users#index'

  scope :dashboard, module: :merchant, as: :dashboard do
    get '/', to: 'users#show'
    resources :items, only: [:index, :new, :edit, :update]
  end

  namespace :merchant do
    resources :items, except: [:show, :index, :new, :edit, :update]

    put '/items/:id/enable', to: 'items#enable', as: :enable_item
    put '/items/:id/disable', to: 'items#disable', as: :disable_item
  end

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show, :create]
    get '/', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :reviews, except: [:show, :new, :create]
  end

  resources :order_items, only: [:create] do
    resources :reviews, only: [:new, :create]
  end

  scope :dashboard, as: :merchant, module: :merchant do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :edit]
    put '/users/:id/enable', to: 'users#enable', as: :enable_user
    put '/users/:id/disable', to: 'users#disable', as: :disable_user
    put 'users/:id/upgrade', to: 'users#upgrade', as: :upgrade_user
    put '/merchant/:id/downgrade', to: 'merchants#downgrade', as: :downgrade_merchant
    get '/dashboard', to: 'dashboard#show'
    resources :merchants, only: [:show, :update] do
      resources :items, except: :show
      put '/items/:id/enable', to: 'items#enable', as: :enable_item
      put '/items/:id/disable', to: 'items#disable', as: :disable_item
    end
    resources :orders, only: [:index, :show, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :items
  has_many :reviews

  has_secure_password

  enum role: ['registered', 'merchant', 'admin']

  validates :name,
    presence: true,
    length: {minimum: 1}

  validates :city,
    presence: true,
    length: {minimum: 1}

  validates :password,
    confirmation: true

  validates :address,
    presence: true,
    length: {minimum: 1}

  validates :email,
    presence: true,
    length: {minimum: 1},
    uniqueness: true

  validates :state,
    presence: true

  validates :zipcode,
    presence: true,
    numericality: {
      only_integer: true
  }


  def self.fastest_merchants
    joins(items: :order_items)
   .select('users.*, avg(order_items.updated_at - order_items.created_at) as fulfillment_time')
   .where(order_items: {fulfilled: true}, disabled: false)
   .group(:id)
   .order('fulfillment_time asc')
   .limit(3)
  end

  def self.slowest_merchants
    joins(items: :order_items)
   .select('users.*, avg(order_items.updated_at - order_items.created_at) as fulfillment_time')
   .where(order_items: {fulfilled: true}, disabled: false)
   .group(:id)
   .order('fulfillment_time desc')
   .limit(3)
  end

  def self.top_merchants_by_revenue
    joins(items: :order_items)
   .select("users.*, sum(order_items.unit_price*order_items.quantity) as revenue")
   .where(order_items: {fulfilled: true}, role: 1, disabled: false)
   .group(:id)
   .order("revenue desc")
   .limit(3)
  end

  def self.merchants_by_items_sold_by_month(limit=1, month=Date.today.month)
    joins(items: {order_items: :order})
    .where('extract(month from order_items.created_at) = ?', month)
    .where.not('orders.status = 3')
    .where("order_items.fulfilled = true")
    .select('users.*, sum(order_items.quantity) as total_quantity')
    .group(:id)
    .order("total_quantity desc")
    .limit(limit)
  end

  def self.merchants_by_revenue_by_month(limit=1, month=Date.today.month)
    joins(items: {order_items: :order})
    .where('extract(month from order_items.created_at) = ?', month)
    .where.not('orders.status = 3')
    .where("order_items.fulfilled = true")
    .select('users.*, sum(order_items.quantity*order_items.unit_price) as total_revenue')
    .group(:id)
    .order("total_revenue desc")
    .limit(limit)
  end

  def self.merchants_by_state_fulfillment_speed(limit=1, state)
    order_ids = Order.joins(:user)
                     .where("users.state = ?", state)
                     .select("orders.*")
                     .pluck(:id)

    self.joins(items: {order_items: :order})
        .select("users.*, avg(order_items.updated_at - order_items.created_at) AS avg_fulfillment_time")
        .where.not('orders.status = 3')
        .where("orders.id in (?)", order_ids)
        .where("order_items.fulfilled = true")
        .group(:id)
        .order("avg_fulfillment_time asc")
        .limit(limit)
  end

  def self.merchants_by_city_fulfillment_speed(limit=1, state, city)
    order_ids = Order.joins(:user)
                     .where("users.state = ?", state)
                     .where("users.city = ?", city)
                     .select("orders.*")
                     .pluck(:id)

    self.joins(items: {order_items: :order})
        .select("users.*, avg(order_items.updated_at - order_items.created_at) AS avg_fulfillment_time")
        .where.not('orders.status = 3')
        .where("orders.id in (?)", order_ids)
        .where("order_items.fulfilled = true")
        .group(:id)
        .order("avg_fulfillment_time asc")
        .limit(limit)
  end

  def has_order_item_in_completed_order(order_item)
    !(orders.joins(:order_items).where(order_items: {id: order_item.id}, status: 'completed').empty?)
  end

  def top_items_for_merchant(limit)
    items.joins(:order_items)
         .where(order_items: { fulfilled: true })
         .select('items.*, sum(order_items.quantity) as total_quantity')
         .group(:id)
         .order('total_quantity desc')
         .limit(limit)
  end

  def items_sold_by_quantity
    items.joins(:order_items)
         .where(order_items: { fulfilled: true })
         .sum('order_items.quantity')
  end

  def items_sold_by_percentage
    items_sold = items_sold_by_quantity
    total_stock = items.sum(:quantity)
    items_sold.to_f / (items_sold + total_stock)
  end

  def top_states(limit)
    items.joins(orders: :user)
         .select('sum(order_items.quantity) as state_quantity, users.state')
         .where(order_items: { fulfilled: true })
         .group('users.state')
         .order('state_quantity desc')
         .limit(limit)
  end

  def top_cities(limit)
    items.joins(orders: :user)
         .select("sum(order_items.quantity) as city_quantity, concat(users.city, ', ', users.state) as location")
         .where(order_items: { fulfilled: true })
         .group('location')
         .order('city_quantity desc')
         .limit(limit)
  end

  def top_customer_by_orders
    items.joins(orders: :user)
         .select('users.id, users.name, count(distinct orders.id) as order_count')
         .where(order_items: { fulfilled: true })
         .group('users.id')
         .order('order_count desc')
         .first
  end

  def top_customer_by_items
    items.joins(orders: :user)
         .select('users.id, users.name, sum(order_items.quantity) as item_count')
         .where(order_items: { fulfilled: true })
         .group('users.id')
         .order('item_count desc')
         .first
  end

  def top_spenders(limit)
    items.joins(orders: :user)
         .select('users.id, users.name, sum(order_items.quantity * order_items.unit_price) as total_spent')
         .where(order_items: { fulfilled: true })
         .group('users.id')
         .order('total_spent desc')
         .limit(limit)
  end

  def self.all_merchants
    where(role: 1)
    .order(id: :asc) # Was getting unstable returns, updated for tests
  end
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController
  def show
    @user = User.find(params[:id])
    @orders = Order.pending_orders(@user)
    redirect_to admin_user_path(@user) if @user.registered?
    render '/merchant/users/show' if @user.merchant?
  end

  def downgrade
    @merchant = User.find(params[:id])
    @merchant.items.each do |item|
      item.update(disabled: 'true')
    end
    @merchant.update(role: 'registered')
    flash[:primary] = 'You have downgraded a merchant'
    redirect_to admin_user_path(@merchant)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.where(role: 'registered')
  end

  def show
    @user = User.find(params[:id])
    redirect_to admin_merchant_path(@user) if @user.role == 'merchant'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User profile has been updated"
      redirect_to admin_user_path(@user)
    else
      flash[:danger] = "There are problems with the provided information."
      render :edit
    end
  end

  def enable
    @user = User.find(params[:id])
    @user.update(disabled: false)
    flash[:primary] = 'You have enabled a user'
    redirect_helper
  end

  def disable
    @user = User.find(params[:id])
    @user.update(disabled: true)
    flash[:primary] = 'You have disabled a user'
    redirect_helper
  end

  def upgrade
    @user = User.find(params[:id])
    @user.update(role: 'merchant')
    flash[:primary] = 'You have upgraded a user'
    redirect_to admin_merchant_path(@user)
  end

  private

  def redirect_helper
    redirect_to admin_users_path if @user.role == 'registered'
    redirect_to merchants_path if @user.role == 'merchant'
  end

  def user_params
    strong_params = params.require(:user).permit(:name, :address, :city, :state, :zipcode, :email, :password, :password_confirmation)
    strong_params[:email] = strong_params[:email].downcase
    strong_params.delete(:password) if strong_params[:password] == ""
    strong_params.delete(:password_confirmation) if strong_params[:password_confirmation] == ""
    strong_params
  end
end

app/controllers/merchant/base_controller.rb
class Merchant::BaseController < ApplicationController
  before_action :require_merchant

  def require_merchant
    render file: '/public/404' unless current_merchant?
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.items
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      flash[:success] = "You have added a new item."
      redirect_to dashboard_items_path
    else
      flash[:danger] = "There are problems with the provided information."
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Your item has been successfully updated."
      redirect_to dashboard_items_path
    else
      flash[:danger] = "There are problems with the provided information."
      render :edit
    end
  end

  def enable
    Item.find(params[:id]).update(disabled: false)
    flash[:success] = "Item ##{params[:id]} is now available for sale."
    redirect_to dashboard_items_path
  end

  def disable
    Item.find(params[:id]).update(disabled: true)
    flash[:warning] = "Item ##{params[:id]} is no longer available for sale."
    redirect_to dashboard_items_path
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:danger] = "Item ##{params[:id]} has been deleted."
    redirect_to dashboard_items_path
  end

  private

  def item_params
    params[:item][:image] = "https://via.placeholder.com/200x300?text=Store64" if params[:item][:image] == ""
    params.require(:item).permit(:name, :description, :image, :price, :quantity)
  end
end

app/controllers/merchant/orders_controller.rb
class Merchant::OrdersController < Merchant::BaseController
  def show
    @order = Order.find(params[:id])
    @customer = @order.user
    render '/orders/show'
  end

  def update
    order_item = OrderItem.find(params[:ordered_item])
    order_item.update(fulfilled: true)
    item = Item.find(order_item.item_id)
    new_quantity = item.quantity - order_item.quantity
    item.update(quantity: new_quantity)
    flash[:success] = "You have fulfilled #{item.name} from order ##{order_item.order_id}"
    order = Order.find(params[:id])
    if order.order_items.where(fulfilled: false).count == 0
      order.update(status: 'completed')
    end
    redirect_to merchant_order_path(order)
  end
end

app/controllers/merchant/users_controller.rb
class Merchant::UsersController < Merchant::BaseController
  def show
    @orders = Order.pending_orders(current_user)
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_or_admin, only: [:edit, :update]
  before_action :require_user, only: [:show]

  def index
    @merchants = User.all_merchants
    @top_merchants_by_revenue = User.top_merchants_by_revenue
    @fastest_merchants = User.fastest_merchants
    @slowest_merchants = User.slowest_merchants
    @top_states = Order.top_states
    @top_cities = Order.top_cities
    @biggest_orders = Order.biggest_orders
    @top_merchants_by_items_sold_this_month = User.merchants_by_items_sold_by_month(10)
    @top_merchants_by_items_sold_last_month = User.merchants_by_items_sold_by_month(10, 1.month.ago.month)
    @top_merchants_by_revenue_this_month = User.merchants_by_revenue_by_month(10)
    @top_merchants_by_revenue_last_month = User.merchants_by_revenue_by_month(10, 1.month.ago.month)
    if current_registered?
      @top_merchants_by_speed_to_your_state = User.merchants_by_state_fulfillment_speed(5, current_user.state)
      @top_merchants_by_speed_to_your_city = User.merchants_by_city_fulfillment_speed(5, current_user.state, current_user.city)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'You are now registered and logged in!'
      redirect_to profile_path
    else
      determine_error
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Your profile has been updated"
      redirect_to profile_path
    else
      determine_error
      render :'users/edit'
    end
  end

  private

  def determine_error
    errors = @user.errors.details
    if errors.has_key?(:email) && errors[:email].first[:error] == :taken
      flash[:danger] = "That email is already registered."
      @user.email = nil
    else
      flash[:danger] = "There were problems with the information provided."
    end
  end

  def user_params
    strong_params = params.require(:user).permit(:name, :address, :city, :state, :zipcode, :email, :password, :password_confirmation)
    strong_params[:email] = strong_params[:email].downcase
    strong_params.delete(:password) if strong_params[:password] == ""
    strong_params.delete(:password_confirmation) if strong_params[:password_confirmation] == ""
    strong_params
  end
end

app/views/merchant/users/show.html.erb
<section>
  <h1 class="text-center">Your Dashboard</h1>
  <%= link_to 'Downgrade Merchant to User', admin_downgrade_merchant_path(@user), method: :put if current_admin?  %>
  <%= render partial: '/users/profile' %>

  <%= link_to 'My Items', dashboard_items_path if current_merchant? %>
  <%= link_to 'My Items', admin_merchant_items_path(@user) if current_admin? %>

  <div class="statistics">

    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: <%=number_to_percentage((@user.items_sold_by_percentage * 100), precision: 0) %>;" aria-valuenow=" <%=@user.items_sold_by_percentage * 100.round(2) %> " aria-valuemin="0" aria-valuemax="100"> <%=number_to_percentage((@user.items_sold_by_percentage * 100), precision: 0) %>
    </div>
  </div>

    <p>Items Sold: You have sold <%= @user.items_sold_by_quantity %> items which is <%=number_to_percentage((@user.items_sold_by_percentage * 100), precision: 0) %> of your total inventory. </p>

    <section class="row">
      <div class="col">

        <h6 class="text-center">Top 5 Items</h6>
          <table class="table table-condensed" id="top-selling-items">
            <thead>
              <tr>
                <th>Name</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
               <% @user.top_items_for_merchant(5).each do |item| %>
              <tr>
                <td> <%= item.name %> </td>
                <td> <%= item.total_quantity %> </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>

      <div class="col">

        <h6 class="text-center">Top 3 States</h6>
          <table class="table table-condensed" id="top-selling-items">
            <thead>
              <tr>
                <th>State</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
              <% @user.top_states(3).each do |state| %>
              <tr>
                <td> <%= state.state %> </td>
                <td> <%= state.state_quantity %> </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>

      <div class="col">

        <h6 class="text-center">Top 3 Cities</h6>
          <table class="table table-condensed" id="top-selling-items">
            <thead>
              <tr>
                <th>City</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
              <% @user.top_cities(3).each do |city| %>
              <tr>
                <td> <%= city.location %> </td>
                <td> <%= city.city_quantity %> </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </section>

    <section class="row">
      <div class="col">

        <h6 class="text-center">Customer With Most Orders:</h6>
          <table class="table table-condensed" id="top-selling-items">
            <thead>
              <tr>
                <th>Name</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @user.top_customer_by_orders.name if @user.top_customer_by_orders %></td>
                <td>  <%= @user.top_customer_by_orders.order_count if @user.top_customer_by_orders %> </td>
              </tr>
            </tbody>
          </table>
      </div>

      <div class="col">

        <h6 class="text-center">Customer with Most Items</h6>
          <table class="table table-condensed" id="top-selling-items">
            <thead>
              <tr>
                <th>Name</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td> <%= @user.top_customer_by_items.name if @user.top_customer_by_items %> </td>
                <td> <%= @user.top_customer_by_items.item_count if @user.top_customer_by_items %> </td>
              </tr>
            </tbody>
          </table>
      </div>

      <div class="col">

        <h6 class="text-center">3 Biggest Spenders</h6>
          <table class="table table-condensed" id="top-selling-items">
            <thead>
              <tr>
                <th>Name</th>
                <th>Total spent</th>
              </tr>
            </thead>
            <tbody>
              <% @user.top_spenders(3).each do |user| %>
              <tr>
                <td> <%= user.name %> </td>
                <td> <%= number_to_currency(user.total_spent) %> </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </section>
  </div>


<div class="container">
  <h6 class="text-center">Pending Orders</h6>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Placed on</th>
        <th>Total Items</th>
        <th>Total Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr class="order-<%= order.id %>">
        <td><%= link_to "##{order.id}", merchant_order_path(order) if current_merchant? %>
         <%= link_to "##{order.id}", admin_order_path(order) if current_admin? %></td>
        <td><%= order.created_at.localtime.strftime("%m-%d-%Y") %> </td>
        <td><%= order.total_items_for_merchant(@user) %> </td>
        <td><%= number_to_currency(order.total_value_for_merchant(@user)) %> </td>
      </tr>
      <% end %>
    </tbody>

  </table>


</section>