config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :items, only: [:index, :show]

  resources :carts, only: [:create]

  resources :users, only: [:create, :update]

  resources :orders, only: :update

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  put '/cart', to: 'carts#update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/merchants', to: 'users#index'

  scope :dashboard, module: :merchant, as: :dashboard do
    get '/', to: 'users#show'
    resources :items, only: [:index, :new, :edit, :update]
  end

  namespace :merchant do
    resources :items, except: [:show, :index, :new, :edit, :update]

    put '/items/:id/enable', to: 'items#enable', as: :enable_item
    put '/items/:id/disable', to: 'items#disable', as: :disable_item
  end

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show, :create]
    get '/', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :reviews, except: [:show, :new, :create]
  end

  resources :order_items, only: [:create] do
    resources :reviews, only: [:new, :create]
  end

  scope :dashboard, as: :merchant, module: :merchant do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :edit]
    put '/users/:id/enable', to: 'users#enable', as: :enable_user
    put '/users/:id/disable', to: 'users#disable', as: :disable_user
    put 'users/:id/upgrade', to: 'users#upgrade', as: :upgrade_user
    put '/merchant/:id/downgrade', to: 'merchants#downgrade', as: :downgrade_merchant
    get '/dashboard', to: 'dashboard#show'
    resources :merchants, only: [:show, :update] do
      resources :items, except: :show
      put '/items/:id/enable', to: 'items#enable', as: :enable_item
      put '/items/:id/disable', to: 'items#disable', as: :disable_item
    end
    resources :orders, only: [:index, :show, :update]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :image

  validates :quantity,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0,
      only_integer: true
  }

  validates :price,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0
  }

  validates :name,
    presence: true,
    length: {minimum: 1}

  validates :description,
    presence: true,
    length: {minimum: 1}

  def self.enabled_items
    Item.where(disabled: false)
  end

  def self.top_items(limit)
    items_by_quantity(limit, "desc")
  end

  def self.worst_items(limit)
    items_by_quantity(limit, "asc")
  end

  def self.items_by_quantity(limit, order)
    Item.select(:id, :name, "SUM(order_items.quantity) as quantity")
    .joins(:order_items)
    .where(order_items: {fulfilled: true})
    .group(:id)
    .order("quantity #{order}")
    .limit(limit)
  end

  def has_reviews?
    !(order_items.joins(:review).empty?)
  end

  def average_review_rating
    order_items.joins(:review).average(:rating)
  end

  def average_fulfillment_time
    if (order_items.count > 0) && (order_items.where({fulfilled: true})).count > 0
      Item.joins(:order_items)
          .where(id: self.id, order_items: {fulfilled: true})
          .select("avg(order_items.updated_at - order_items.created_at) as fulfillment_time")
          .group(:id)[0]
          .fulfillment_time
    elsif order_items.count > 0
      "This item has not been fulfilled"
    else
      "Never been ordered"
    end
  end

  def ordered?
    order_items.count > 0
  end

  def subtotal(quantity)
    price * quantity
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  def index
    @merchant = User.find(params[:merchant_id])
    @items = @merchant.items
    render :'merchant/items/index'
  end

  def new
    @merchant = User.find(params[:merchant_id])
    @item = @merchant.items.new
  end

  def create
    @merchant = User.find(params[:merchant_id])
    @item = @merchant.items.new(item_params)
    if @item.save
      flash[:success] = "You have added an item."
      redirect_to admin_merchant_items_path(@merchant)
    else
      flash[:danger] = "There are problems with the provided information."
      render :new
    end
  end

  def edit
    @merchant = User.find(params[:merchant_id])
    @item = Item.find(params[:id])
  end

  def update
    @merchant = User.find(params[:merchant_id])
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Item ##{@item.id} has successfully been updated."
      redirect_to admin_merchant_items_path(@merchant)
    else
      flash[:danger] = "There are problems with the provided information."
      render :edit
    end
  end

  def destroy
    item = Item.destroy(params[:id])
    flash[:danger] = "Item ##{params[:id]} has been deleted."
    redirect_to admin_merchant_items_path(item.user_id)
  end

  def enable
    Item.find(params[:id]).update(disabled: false)
    flash[:success] = "Item ##{params[:id]} is now available for sale."
    redirect_to admin_merchant_items_path(params[:merchant_id])
  end

  def disable
    Item.find(params[:id]).update(disabled: true)
    flash[:warning] = "Item ##{params[:id]} is no longer available for sale."
    redirect_to admin_merchant_items_path(params[:merchant_id])
  end

  private

  def item_params
    params[:item][:image] = "https://via.placeholder.com/200x300?text=Store64" if params[:item][:image] == ""
    params.require(:item).permit(:name, :description, :image, :price, :quantity)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.enabled_items
    @top_items = Item.top_items(5)
    @worst_items = Item.worst_items(5)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.items
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      flash[:success] = "You have added a new item."
      redirect_to dashboard_items_path
    else
      flash[:danger] = "There are problems with the provided information."
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Your item has been successfully updated."
      redirect_to dashboard_items_path
    else
      flash[:danger] = "There are problems with the provided information."
      render :edit
    end
  end

  def enable
    Item.find(params[:id]).update(disabled: false)
    flash[:success] = "Item ##{params[:id]} is now available for sale."
    redirect_to dashboard_items_path
  end

  def disable
    Item.find(params[:id]).update(disabled: true)
    flash[:warning] = "Item ##{params[:id]} is no longer available for sale."
    redirect_to dashboard_items_path
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:danger] = "Item ##{params[:id]} has been deleted."
    redirect_to dashboard_items_path
  end

  private

  def item_params
    params[:item][:image] = "https://via.placeholder.com/200x300?text=Store64" if params[:item][:image] == ""
    params.require(:item).permit(:name, :description, :image, :price, :quantity)
  end
end

app/views/items/index.html.erb
<section class="container" id="statistics-wrapper">
  <section class="row">
    <div class="col">

      <h1 class="text-center">Top Selling Items</h1>
        <table class="table table-borderless" id="top-selling-items">
          <thead>
            <tr>
              <th class="w-80">Name</th>
              <th class="w-20">Quantity</th>
            </tr>
          </thead>
          <tbody class="top-items-body">
            <% @top_items.each do |item| %>
            <tr class="top-items">
              <td> <%= item.name %> </td>
              <td> <%= item.quantity %> </td>
            </tr>
            <% end %>
          </tbody>
        </table>
     </div>

<div class="col">

  <h1 class="text-center">Worst Selling Items</h1>
    <table class="table table-borderless" id="worst-selling-items">
      <thead>
        <tr>
          <th class="w-80">Name</th>
          <th class="w-20">Quantity</th>
        </tr>
      </thead>
      <tbody>
        <% @worst_items.each do |item| %>
        <tr class="worst-items">
          <td> <%= item.name %> </td>
          <td> <%= item.quantity %> </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  </section>


</section>


<section class="container">
  <section class="row" id="cards_wrapper">
    <% @items.each do |item| %>
    <div class='card col-12 col-md-6 col-lg-4 col-xl-3' id="item-<%= item.id %>">
      <%= link_to image_tag(item.image, class: "card-img-top", alt: "#{item.name} image"), item_path(item), id: "picture-#{item.id}" %>
      <div class="card-body">
        <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
        <h6 class="merchant-name"><%= item.user.name %></h6>
        <p class="card-text"><%= item.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Current Price: <%= number_to_currency(item.price) %></li>
        <li class="list-group-item">Stock: <%= item.quantity %></li>
        <% if item.has_reviews? %>
          <li class="list-group-item">Average Review Rating: <%= item.average_review_rating %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </section>
</section>

app/views/items/show.html.erb
<section class="container" id="item-show-container">
  <section class="row">
    <section class="col-12 col-md-6 col-lg-6">
      <%= image_tag @item.image, class: "img-fluid" %>
    </section>
    <section class="col-12 col-md-6 col-lg-6">
      <h2><%= @item.name %></h2>
      <h4><%= @item.user.name %></h4>
      <p>Current Price: <%= number_to_currency(@item.price) %></p>
      <p>Stock: <%= @item.quantity %></p>
      <p>Average Fulfillment Time: <%= time_string(@item.average_fulfillment_time) %></p>
      <% if @item.has_reviews? %>
        <p>Average Review Rating: <%= @item.average_review_rating %></p>
      <% end %>
      <%= link_to "Add to Shopping Cart", carts_path(item_id: @item.id), method: :post unless current_user && (current_user.admin? || current_user.merchant?) %>
    </section>
  </section>
  <section class="row">
    <h6>Item Description:</h6>
    <%= @item.description %>
  </section>
  <section id='reviews'>
    <h1>Reviews</h1>
    <% @item.order_items.each do |order_item| %>
      <% if order_item.review %>
        <section id="reviews-<%= order_item.review.id %>">
          <h2><%= order_item.review.title %></h2>
          <h4><%= order_item.review.user.name %></h4>
          <h6>Rating: <%= order_item.review.rating %></h6>
          <p><%= order_item.review.description %></p>
          <p>Created At: <%= order_item.review.created_at %></p>
          <% unless order_item.review.created_at == order_item.review.updated_at %>
            <p>Updated At: <%= order_item.review.updated_at %></p>
          <% end %>
        </section>
      <% end %>
    <% end %>
  </section>
</section>